# Sử dụng image chính thức của Python
FROM python:3.9

# Đặt biến môi trường
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Thiết lập thư mục làm việc
WORKDIR /app

# Cài đặt các dependencies
COPY requirements.txt /app/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Copy toàn bộ mã nguồn vào container
COPY . /app/

# Chạy lệnh quản lý của Django
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
